# Generated by Django 4.2.7 on 2025-11-28 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_pokemonmove_wildpokemonencounter'),
        ('usuario', '0002_player_bag_pokedex'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.IntegerField(default=1)),
                ('current_hp', models.IntegerField()),
                ('experience', models.IntegerField(default=0)),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('special_attack', models.IntegerField()),
                ('special_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('moves', models.ManyToManyField(limit_choices_to=4, related_name='player_pokemons', to='pokemon.move')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to='usuario.player')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemon')),
            ],
            options={
                'db_table': 'player_pokemons',
            },
        ),
    ]
