# Generated by Django 4.2.7 on 2025-11-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_pokemonmove_wildpokemonencounter'),
        ('usuario', '0003_playerpokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerpokemon',
            name='attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerpokemon',
            name='current_hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerpokemon',
            name='defense',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerpokemon',
            name='hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerpokemon',
            name='moves',
            field=models.ManyToManyField(related_name='player_pokemons', to='pokemon.move'),
        ),
        migrations.AlterField(
            model_name='playerpokemon',
            name='special_attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerpokemon',
            name='special_defense',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerpokemon',
            name='speed',
            field=models.IntegerField(default=0),
        ),
    ]
