# Generated by Django 4.2.7 on 2025-11-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_playerpokemon_attack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerpokemon',
            name='in_team',
            field=models.BooleanField(default=True),
        ),
    ]
