# Generated by Django 4.2.7 on 2025-11-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_playerpokemon_in_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='hyper_potions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bag',
            name='super_potions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bag',
            name='ultra_balls',
            field=models.IntegerField(default=0),
        ),
    ]
