# Generated by Django 4.2.7 on 2025-11-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_bag_hyper_potions_bag_super_potions_bag_ultra_balls'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerpokemon',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
