# Generated by Django 4.2.7 on 2025-11-29 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_shopitem'),
        ('usuario', '0007_playerpokemon_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wild_level', models.IntegerField()),
                ('wild_current_hp', models.IntegerField()),
                ('wild_max_hp', models.IntegerField()),
                ('state', models.CharField(choices=[('active', 'Activa'), ('won', 'Ganada'), ('lost', 'Perdida'), ('fled', 'Huyó')], default='active', max_length=10)),
                ('turn', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='usuario.player')),
                ('player_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_battles', to='usuario.playerpokemon')),
                ('wild_moves', models.ManyToManyField(related_name='wild_battles', to='pokemon.move')),
                ('wild_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemon')),
            ],
            options={
                'db_table': 'battles',
            },
        ),
    ]
