# Generated by Django 4.2.7 on 2025-12-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_battle'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerpokemon',
            name='just_evolved',
            field=models.BooleanField(default=False),
        ),
    ]
