# Generated by Django 4.2.7 on 2025-12-01 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_shopitem'),
        ('usuario', '0009_playerpokemon_just_evolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='battle_type',
            field=models.CharField(choices=[('wild', 'Salvaje'), ('trainer', 'Entrenador')], default='wild', max_length=10),
        ),
        migrations.AddField(
            model_name='battle',
            name='current_trainer_pokemon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battle',
            name='trainer_dialogue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='trainer_money_reward',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battle',
            name='trainer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='trainer_sprite',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='trainer_team',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('trainer_type', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado'), ('gym_leader', 'Líder de Gimnasio'), ('elite_four', 'Alto Mando'), ('champion', 'Campeón')], max_length=20)),
                ('sprite', models.URLField(blank=True, null=True)),
                ('dialogue_before', models.TextField(blank=True, null=True)),
                ('dialogue_after', models.TextField(blank=True, null=True)),
                ('money_reward', models.IntegerField(default=100)),
                ('min_level', models.IntegerField(default=1)),
                ('max_level', models.IntegerField(default=10)),
                ('team_size', models.IntegerField(default=1)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to='pokemon.location')),
            ],
            options={
                'db_table': 'trainers',
            },
        ),
    ]
