# Generated by Django 4.2.7 on 2025-12-01 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_shopitem'),
        ('usuario', '0010_battle_battle_type_battle_current_trainer_pokemon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='wild_current_hp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='wild_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='wild_max_hp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='wild_pokemon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemon'),
        ),
    ]
