# Generated by Django 4.2.7 on 2025-12-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_alter_battle_wild_current_hp_alter_battle_wild_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerpokemon',
            name='moves_pp',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
