# Generated by Django 4.2.7 on 2025-12-02 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_shopitem'),
        ('usuario', '0012_playerpokemon_moves_pp'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='battle_format',
            field=models.CharField(blank=True, choices=[('1vs1', '1 Pokémon por jugador'), ('2vs2', '2 Pokémon por jugador')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='current_turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_turn_battles', to='usuario.player'),
        ),
        migrations.AddField(
            model_name='battle',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='battle',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvp_battles_as_player1', to='usuario.player'),
        ),
        migrations.AddField(
            model_name='battle',
            name='player1_current_pokemon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battle',
            name='player1_team',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='battle',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvp_battles_as_player2', to='usuario.player'),
        ),
        migrations.AddField(
            model_name='battle',
            name='player2_current_pokemon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battle',
            name='player2_team',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='battle',
            name='room_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_battles', to='usuario.player'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='battle_type',
            field=models.CharField(choices=[('wild', 'Salvaje'), ('trainer', 'Entrenador'), ('pvp', 'PvP')], default='wild', max_length=10),
        ),
        migrations.AlterField(
            model_name='battle',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='usuario.player'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='player_pokemon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_battles', to='usuario.playerpokemon'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='state',
            field=models.CharField(choices=[('waiting', 'Esperando'), ('active', 'Activa'), ('won', 'Ganada'), ('lost', 'Perdida'), ('fled', 'Huyó'), ('draw', 'Empate')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='battle',
            name='wild_moves',
            field=models.ManyToManyField(blank=True, related_name='wild_battles', to='pokemon.move'),
        ),
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['room_code'], name='battles_room_co_5c022e_idx'),
        ),
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['state', 'battle_type'], name='battles_state_6a870d_idx'),
        ),
    ]
