# Generated by Django 4.2.7 on 2025-11-28 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('normal', 'Normal'), ('fire', 'Fuego'), ('water', 'Agua')], max_length=10)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('accuracy', models.IntegerField(blank=True, null=True)),
                ('pp', models.IntegerField()),
                ('damage_class', models.CharField(choices=[('physical', 'Físico'), ('special', 'Especial'), ('status', 'Estado')], max_length=10)),
            ],
            options={
                'db_table': 'moves',
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokedex_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('type1', models.CharField(choices=[('normal', 'Normal'), ('fire', 'Fuego'), ('water', 'Agua'), ('electric', 'Eléctrico'), ('grass', 'Planta'), ('ice', 'Hielo'), ('fighting', 'Lucha'), ('poison', 'Veneno'), ('ground', 'Tierra'), ('flying', 'Volador'), ('psychic', 'Psíquico'), ('bug', 'Bicho'), ('rock', 'Roca'), ('ghost', 'Fantasma'), ('dragon', 'Dragón'), ('dark', 'Siniestro'), ('steel', 'Acero'), ('fairy', 'Hada')], max_length=10)),
                ('type2', models.CharField(blank=True, choices=[('normal', 'Normal'), ('fire', 'Fuego'), ('water', 'Agua'), ('electric', 'Eléctrico'), ('grass', 'Planta'), ('ice', 'Hielo'), ('fighting', 'Lucha'), ('poison', 'Veneno'), ('ground', 'Tierra'), ('flying', 'Volador'), ('psychic', 'Psíquico'), ('bug', 'Bicho'), ('rock', 'Roca'), ('ghost', 'Fantasma'), ('dragon', 'Dragón'), ('dark', 'Siniestro'), ('steel', 'Acero'), ('fairy', 'Hada')], max_length=10, null=True)),
                ('base_hp', models.IntegerField()),
                ('base_attack', models.IntegerField()),
                ('base_defense', models.IntegerField()),
                ('base_special_attack', models.IntegerField()),
                ('base_special_defense', models.IntegerField()),
                ('base_speed', models.IntegerField()),
                ('experience_growth', models.IntegerField()),
                ('evolution_level', models.IntegerField(blank=True, null=True)),
                ('sprite_front', models.URLField()),
                ('sprite_back', models.URLField()),
                ('evolves_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon.pokemon')),
            ],
            options={
                'db_table': 'pokemon',
                'ordering': ['pokedex_id'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location_type', models.CharField(choices=[('town', 'Pueblo'), ('route', 'Ruta')], max_length=10)),
                ('connected_locations', models.ManyToManyField(blank=True, to='pokemon.location')),
            ],
            options={
                'db_table': 'locations',
            },
        ),
    ]
