# Generated by Django 4.2.7 on 2025-11-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('fire', 'Fuego'), ('water', 'Agua'), ('electric', 'Eléctrico'), ('grass', 'Planta'), ('ice', 'Hielo'), ('fighting', 'Lucha'), ('poison', 'Veneno'), ('ground', 'Tierra'), ('flying', 'Volador'), ('psychic', 'Psíquico'), ('bug', 'Bicho'), ('rock', 'Roca'), ('ghost', 'Fantasma'), ('dragon', 'Dragón'), ('dark', 'Siniestro'), ('steel', 'Acero'), ('fairy', 'Hada')], max_length=10),
        ),
    ]
