# Generated by Django 4.2.7 on 2025-11-28 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_alter_move_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.move')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves_by_level', to='pokemon.pokemon')),
            ],
            options={
                'db_table': 'pokemon_moves',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='WildPokemonEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_level', models.IntegerField()),
                ('max_level', models.IntegerField()),
                ('rarity', models.CharField(choices=[('common', 'Común'), ('uncommon', 'Poco Común'), ('rare', 'Raro'), ('very_rare', 'Muy Raro')], max_length=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wild_pokemons', to='pokemon.location')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemon')),
            ],
            options={
                'db_table': 'wild_pokemon_encounters',
                'unique_together': {('location', 'pokemon')},
            },
        ),
    ]
