# Generated by Django 4.2.7 on 2025-11-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_pokemonmove_wildpokemonencounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('item_type', models.CharField(choices=[('potion', 'Poción'), ('pokeball', 'Pokéball'), ('super_potion', 'Superpoción'), ('hyper_potion', 'Hiperpoción'), ('ultra_ball', 'Ultraball')], max_length=20)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('effect_value', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'shop_items',
            },
        ),
    ]
